spring:
  application:
    name: ai-sheet-helper
  webflux:
    multipart:
      max-parts: 1
      max-disk-usage-per-part: 10MB
      max-in-memory-size: 10MB
      max-headers-size: 2MB
  codec:
    max-in-memory-size: 10MB

  ai:
    ollama:
      chat:
        model: qwen2.5:3b # llama3.2-vision
      base-url: ${ai.ollama.url}

server:
  compression:
    enabled: true

gateway:
  static-file-path: ${STATIC_FILE_PATH:/tmp}
  default-file: index.html
  spa-path: /ui

ai:
  ollama:
    url: http://${OLLAMA_HOST:localhost}:11434

cors:
  allowed-origin: http://localhost:5173

custom:
  ai:
    response-timeout: 2m
